# ── IP Module ────────────────────────────────────────────────────────────────
CONFIG_IP_MODULE=y
CONFIG_IP_MODULE_LOG_LEVEL=3
CONFIG_IP_MODULE_THREAD_STACK_SIZE=2048
CONFIG_IP_MODULE_THREAD_PRIORITY=5

# ── State Machine Framework ──────────────────────────────────────────────────
CONFIG_SMF=y
CONFIG_SMF_ANCESTOR_SUPPORT=n

# ── Logging ──────────────────────────────────────────────────────────────────
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# ── Threading ────────────────────────────────────────────────────────────────
CONFIG_MULTITHREADING=y

CONFIG_UART_CONSOLE=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_LOG_BACKEND_RTT=y